name: Deploy production from ARM template

# Controls when the workflow will run
on:
  push:
    branches:
      - production
    paths:
      - tsi-dataops-dev/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
