name: Azure IaC prod

on:
  push:
    branches:
      - production
    paths:
      - iac/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.7
    steps:
      - uses: actions/checkout@v2
      - name: Terraform initialization
        run: |
          cd iac/
          terraform init
          terraform validate
          terraform apply -auto-approve
