name: Azure IaC prod

on:
  push:
    branches:
      - production
    paths:
      - iac/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.7
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
  
      - name: Terraform initialization
        run: |
          cd iac/
          terraform init
          terraform validate
          terraform destroy -auto-approve
